//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.08 at 10:41:17 AM IST 
//


package com.htc.jaxb.helpers;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for doctor_ty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="doctor_ty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="doctorid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="doctorname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="speciality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="experience" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *       &lt;attribute name="regno" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "doctor_ty", propOrder = {
		"doctorid",
		"doctorname",
		"speciality",
		"experience"
})
public class DoctorTy {

	@XmlElement(required = true)
	protected String doctorid;
	@XmlElement(required = true)
	protected String doctorname;
	@XmlElement(required = true)
	protected String speciality;
	@XmlElement(required = true)
	protected BigInteger experience;
	@XmlAttribute(name = "regno")
	protected String regno;

	/**
	 * Gets the value of the doctorid property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getDoctorid() {
		return doctorid;
	}

	/**
	 * Sets the value of the doctorid property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setDoctorid(String value) {
		this.doctorid = value;
	}

	/**
	 * Gets the value of the doctorname property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getDoctorname() {
		return doctorname;
	}

	/**
	 * Sets the value of the doctorname property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setDoctorname(String value) {
		this.doctorname = value;
	}

	/**
	 * Gets the value of the speciality property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getSpeciality() {
		return speciality;
	}

	/**
	 * Sets the value of the speciality property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setSpeciality(String value) {
		this.speciality = value;
	}

	/**
	 * Gets the value of the experience property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link BigInteger }
	 *     
	 */
	public BigInteger getExperience() {
		return experience;
	}

	/**
	 * Sets the value of the experience property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link BigInteger }
	 *     
	 */
	public void setExperience(BigInteger value) {
		this.experience = value;
	}

	/**
	 * Gets the value of the regno property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getRegno() {
		return regno;
	}

	/**
	 * Sets the value of the regno property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setRegno(String value) {
		this.regno = value;
	}

	@Override
	public String toString() {
		return "DoctorTy [doctorid=" + doctorid + ", doctorname=" + doctorname + ", speciality=" + speciality
				+ ", experience=" + experience + ", regno=" + regno + "]";
	}

}
