//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.13 at 09:31:22 AM IST 
//


package com.htc.jaxb.serviceHelpers;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.htc.jaxb.serviceHelpers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Service_QNAME = new QName("http://www.htc.com/service", "service");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.htc.jaxb.serviceHelpers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceTy }
     * 
     */
    public ServiceTy createServiceTy() {
        return new ServiceTy();
    }

    /**
     * Create an instance of {@link AutomobileTy }
     * 
     */
    public AutomobileTy createAutomobileTy() {
        return new AutomobileTy();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceTy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.htc.com/service", name = "service")
    public JAXBElement<ServiceTy> createService(ServiceTy value) {
        return new JAXBElement<ServiceTy>(_Service_QNAME, ServiceTy.class, null, value);
    }

}
