
package com.htc.webservice.helper;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TouristService", targetNamespace = "http://webservice.htc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TouristService {


    /**
     * 
     * @param state
     * @return
     *     returns java.util.List<com.htc.webservice.helper.TouristPlace>
     */
    @WebMethod
    @WebResult(name = "placeList", targetNamespace = "")
    @RequestWrapper(localName = "getAllTouristPlaces", targetNamespace = "http://webservice.htc.com/", className = "com.htc.webservice.helper.GetAllTouristPlaces")
    @ResponseWrapper(localName = "getAllTouristPlacesResponse", targetNamespace = "http://webservice.htc.com/", className = "com.htc.webservice.helper.GetAllTouristPlacesResponse")
    @Action(input = "http://webservice.htc.com/TouristService/getAllTouristPlacesRequest", output = "http://webservice.htc.com/TouristService/getAllTouristPlacesResponse")
    public List<TouristPlace> getAllTouristPlaces(
        @WebParam(name = "state", targetNamespace = "")
        String state);

    /**
     * 
     * @param placeName
     * @return
     *     returns com.htc.webservice.helper.TouristPlace
     */
    @WebMethod
    @WebResult(name = "touristPlace", targetNamespace = "")
    @RequestWrapper(localName = "getTouristPlaceDetails", targetNamespace = "http://webservice.htc.com/", className = "com.htc.webservice.helper.GetTouristPlaceDetails")
    @ResponseWrapper(localName = "getTouristPlaceDetailsResponse", targetNamespace = "http://webservice.htc.com/", className = "com.htc.webservice.helper.GetTouristPlaceDetailsResponse")
    @Action(input = "http://webservice.htc.com/TouristService/getTouristPlaceDetailsRequest", output = "http://webservice.htc.com/TouristService/getTouristPlaceDetailsResponse")
    public TouristPlace getTouristPlaceDetails(
        @WebParam(name = "placeName", targetNamespace = "")
        String placeName);

}
