//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.12 at 08:05:59 PM IST 
//


package com.htc.jaxb.empHelper;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.htc.jaxb.empHelper package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Employees_QNAME = new QName("http://www.htc.com/employee", "employees");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.htc.jaxb.empHelper
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmployeesTy }
     * 
     */
    public EmployeesTy createEmployeesTy() {
        return new EmployeesTy();
    }

    /**
     * Create an instance of {@link EmployeeTy }
     * 
     */
    public EmployeeTy createEmployeeTy() {
        return new EmployeeTy();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmployeesTy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.htc.com/employee", name = "employees")
    public JAXBElement<EmployeesTy> createEmployees(EmployeesTy value) {
        return new JAXBElement<EmployeesTy>(_Employees_QNAME, EmployeesTy.class, null, value);
    }

}
