
package com.htc.soapjdbcclient.helper;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TouristServiceImplService", targetNamespace = "http://service.soapjdbc.htc.com/", wsdlLocation = "http://localhost:1235/touristService?wsdl")
public class TouristServiceImplService
    extends Service
{

    private final static URL TOURISTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOURISTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TOURISTSERVICEIMPLSERVICE_QNAME = new QName("http://service.soapjdbc.htc.com/", "TouristServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1235/touristService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOURISTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TOURISTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TouristServiceImplService() {
        super(__getWsdlLocation(), TOURISTSERVICEIMPLSERVICE_QNAME);
    }

    public TouristServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOURISTSERVICEIMPLSERVICE_QNAME, features);
    }

    public TouristServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TOURISTSERVICEIMPLSERVICE_QNAME);
    }

    public TouristServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOURISTSERVICEIMPLSERVICE_QNAME, features);
    }

    public TouristServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TouristServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TouristService
     */
    @WebEndpoint(name = "TouristServiceImplPort")
    public TouristService getTouristServiceImplPort() {
        return super.getPort(new QName("http://service.soapjdbc.htc.com/", "TouristServiceImplPort"), TouristService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TouristService
     */
    @WebEndpoint(name = "TouristServiceImplPort")
    public TouristService getTouristServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soapjdbc.htc.com/", "TouristServiceImplPort"), TouristService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOURISTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TOURISTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TOURISTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
